export const data = [
  {
    id: 101,
    itemname: "Chicken momo",
    category: "momo",
    price: 100,
  },
  {
    id: 102,
    itemname: "Chicken Biryani",
    category: "Biryani",
    price: 1000,
  },
  {
    id: 103,
    itemname: "Chicken Roast",
    category: "Roast",
    price: 500,
  },
  {
    id: 104,
    itemname: "Chicken Burger",
    category: "Burger",
    price: 250,
  },
  {
    id: 105,
    itemname: "Chicken Chowmien",
    category: "Chowmien",
    price: 300,
  },
  {
    id: 106,
    itemname: "Chicken Current",
    category: "Current",
    price: 300,
  },
  {
    id: 107,
    itemname: "Chicken Spaghetti",
    category: "Spaghetti",
    price: 300,
  },

  {
    id: 201,
    itemname: "Chawsai panipuri",
    category: "Panipuri",
    price: 150,
    special: true,
  },
  {
    id: 202,
    itemname: "Chicken tandoori",
    category: "Tandoori",
    price: 1250,
    special: true,
  },
  {
    id: 203,
    itemname: "Dahi chaat",
    category: "Chaat",
    price: 95,
    special: true,
  },
  {
    id: 204,
    itemname: "special dahi",
    category: "Dahi",
    price: 250,
    special: true,
  },
  {
    id: 205,
    itemname: "mojito",
    category: "Drinks",
    price: 300,
    special: true,
  },
  {
    id: 206,
    itemname: "Veg Momo",
    category: "Momo",
    price: 300,
  },
  {
    id: 207,
    itemname: "Buff Momo",
    category: "Momo",
    price: 300,
  },
  {
    id: 208,
    itemname: "Coca Cola",
    category: "Drinks",
    price: 300,
  },
  {
    id: 209,
    itemname: "Kothey Momo",
    category: "momo",
    price: 300,
  },
  {
    id: 210,
    itemname: "Veg Burger",
    category: "Burger",
    price: 300,
  },
  {
    id: 211,
    itemname: "fanta",
    category: "Drinks",
    price: 300,
  },
  {
    id: 212,
    itemname: "Ruslan",
    category: "Hard Drinks",
    price: 300,
  },
];
