export const menudata = [
  {
    index: 0,
    itemname: "Burger",
    types: [
      { typeid: 11, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 12, itemname: "Beef Ham-Burger", size: "medium" },
      { typeid: 13, itemname: "Beef Ham-Burger", size: "large" },
      { typeid: 14, itemname: "Beef Ham-Burger", size: "medium" },
      { typeid: 15, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 16, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 17, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 18, itemname: "Beef Ham-Burger", size: "small" },
    ],
  },
  {
    index: 1,
    itemname: "Momo",
    types: [
      { typeid: 21, itemname: "Chicken Momo Steam", size: "small" },
      { typeid: 22, itemname: "Veg Momo Steam", size: "medium" },
      { typeid: 23, itemname: "Chicken Kothey Momo", size: "large" },
      { typeid: 24, itemname: "Chicken chilli", size: "medium" },
      { typeid: 25, itemname: "Veg Kothey Momo", size: "small" },
      { typeid: 26, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 27, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 28, itemname: "Beef Ham-Burger", size: "small" },
    ],
  },
  {
    index: 2,
    itemname: "Chowmein",
    types: [
      { typeid: 31, itemname: "Veg Chowmein", size: "small" },
      { typeid: 32, itemname: "Chicken Chowmein", size: "medium" },
      { typeid: 33, itemname: "Pork Chowmein", size: "large" },
      { typeid: 34, itemname: "Beef Ham-Burger", size: "medium" },
      { typeid: 35, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 36, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 37, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 38, itemname: "Beef Ham-Burger", size: "small" },
    ],
  },
  {
    index: 3,
    itemname: "Khana Thali",
    types: [
      { typeid: 41, itemname: "Veg Thali", size: "small" },
      { typeid: 42, itemname: "Chicken Thali", size: "medium" },
      { typeid: 43, itemname: "Mutton Thali", size: "large" },
      { typeid: 44, itemname: "Beef Ham-Burger", size: "medium" },
      { typeid: 45, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 46, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 47, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 48, itemname: "Beef Ham-Burger", size: "small" },
    ],
  },
  {
    index: 4,
    itemname: "Biryani",
    types: [
      { typeid: 51, itemname: "Chicken Biryani", size: "small" },
      { typeid: 52, itemname: "Veg Biryani", size: "medium" },
      { typeid: 53, itemname: "Mutton Biryani", size: "large" },
      { typeid: 54, itemname: "Beef Ham-Burger", size: "medium" },
      { typeid: 55, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 56, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 57, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 58, itemname: "Beef Ham-Burger", size: "small" },
    ],
  },
];
