export const menudata = [
  {
    index: 0,
    itemname: "Burger",
    types: [
      { typeid: 1, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 2, itemname: "Beef Ham-Burger", size: "medium" },
      { typeid: 3, itemname: "Beef Ham-Burger", size: "large" },
      { typeid: 4, itemname: "Beef Ham-Burger", size: "medium" },
      { typeid: 5, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 6, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 7, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 8, itemname: "Beef Ham-Burger", size: "small" },
    ],
  },
  {
    index: 1,
    itemname: "Momo",
    types: [
      { typeid: 1, itemname: "Chicken Momo Steam", size: "small" },
      { typeid: 2, itemname: "Veg Momo Steam", size: "medium" },
      { typeid: 3, itemname: "Chicken Kothey Momo", size: "large" },
      { typeid: 4, itemname: "Chicken chilli", size: "medium" },
      { typeid: 5, itemname: "Veg Kothey Momo", size: "small" },
      { typeid: 6, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 7, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 8, itemname: "Beef Ham-Burger", size: "small" },
    ],
  },
  {
    index: 2,
    itemname: "Chowmein",
    types: [
      { typeid: 1, itemname: "Veg Chowmein", size: "small" },
      { typeid: 2, itemname: "Chicken Chowmein", size: "medium" },
      { typeid: 3, itemname: "Pork Chowmein", size: "large" },
      { typeid: 4, itemname: "Beef Ham-Burger", size: "medium" },
      { typeid: 5, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 6, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 7, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 8, itemname: "Beef Ham-Burger", size: "small" },
    ],
  },
  {
    index: 3,
    itemname: "Khana Thali",
    types: [
      { typeid: 1, itemname: "Veg Thali", size: "small" },
      { typeid: 2, itemname: "Chicken Thali", size: "medium" },
      { typeid: 3, itemname: "Mutton Thali", size: "large" },
      { typeid: 4, itemname: "Beef Ham-Burger", size: "medium" },
      { typeid: 5, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 6, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 7, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 8, itemname: "Beef Ham-Burger", size: "small" },
    ],
  },
  {
    index: 4,
    itemname: "Biryani",
    types: [
      { typeid: 1, itemname: "Chicken Biryani", size: "small" },
      { typeid: 2, itemname: "Veg Biryani", size: "medium" },
      { typeid: 3, itemname: "Mutton Biryani", size: "large" },
      { typeid: 4, itemname: "Beef Ham-Burger", size: "medium" },
      { typeid: 5, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 6, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 7, itemname: "Beef Ham-Burger", size: "small" },
      { typeid: 8, itemname: "Beef Ham-Burger", size: "small" },
    ],
  },
];
